modLoader = "javafml"
loaderVersion = "[41,)"
license = "ARR"
issueTrackerURL="https://github.com/dimadencep/Illuminations-forge/issues"

[[mods]]
modId = "illuminations"
version = "1.19.2-1.10.9.20"
displayName = "Illuminations"
logoFile= "logo.png"
authors = "doctor4t, dima_dencep"
displayURL = "https://illuminations.uuid.gg/"
description = "Fireflies, other illuminations to make your world more enjoyable in darkness and player cosmetics."

[[dependencies.illuminations]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.illuminations]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.illuminations]]
modId = "cloth_config"
mandatory = false
versionRange = "[7.0,)"
ordering = "NONE"
side = "BOTH"